// Generated by CoffeeScript 1.12.7
(function() {
  console.log("Hey, you!\nYeah, you, right there!\nThere should've been a carousel here,\n    a really nicee carousel, each containing\n    a paragraph of the \"About me\" section.");

  console.log("But the DOM is kind of a bitch, isn't it?\nIt doesn't find the element you've\n    *verified* that it loads, and\n    you spend hours trying to debug\n    something that apparently can't be\n    debugged.");

}).call(this);
